// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package grpc.services.schedule;

public final class ScheduleOuterClass {
  private ScheduleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedule_Schedule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedule_Schedule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016schedule.proto\022\010schedule\"^\n\010Schedule\022\014" +
      "\n\004name\030\001 \001(\t\022\020\n\010position\030\002 \001(\t\022\014\n\004date\030\003" +
      " \001(\t\022\022\n\nstart_time\030\004 \001(\t\022\020\n\010end_time\030\005 \001" +
      "(\tB\032\n\026grpc.services.scheduleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_schedule_Schedule_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schedule_Schedule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedule_Schedule_descriptor,
        new java.lang.String[] { "Name", "Position", "Date", "StartTime", "EndTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
