// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.services.service2;

public interface ScheduleChangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ScheduleChangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Field for the name for changing schedules
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Field for the name for changing schedules
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Field for the position for changing schedules
   * </pre>
   *
   * <code>string position = 2;</code>
   */
  java.lang.String getPosition();
  /**
   * <pre>
   * Field for the position for changing schedules
   * </pre>
   *
   * <code>string position = 2;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <pre>
   * Field for the date for changing schedules
   * </pre>
   *
   * <code>string date = 3;</code>
   */
  java.lang.String getDate();
  /**
   * <pre>
   * Field for the date for changing schedules
   * </pre>
   *
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <pre>
   * Field for the start time for changing schedules
   * </pre>
   *
   * <code>string start_time = 4;</code>
   */
  java.lang.String getStartTime();
  /**
   * <pre>
   * Field for the start time for changing schedules
   * </pre>
   *
   * <code>string start_time = 4;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <pre>
   * Field for the end time for changing schedules
   * </pre>
   *
   * <code>string end_time = 5;</code>
   */
  java.lang.String getEndTime();
  /**
   * <pre>
   * Field for the end time for changing schedules
   * </pre>
   *
   * <code>string end_time = 5;</code>
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();
}
