// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

/**
 * <pre>
 * Definition of the 'AvailabilityResponse' message with its fields
 * </pre>
 *
 * Protobuf type {@code service3.AvailabilityResponse}
 */
public  final class AvailabilityResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.AvailabilityResponse)
    AvailabilityResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AvailabilityResponse.newBuilder() to construct.
  private AvailabilityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AvailabilityResponse() {
    isAvailable_ = false;
    workingHours_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AvailabilityResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isAvailable_ = input.readBool();
            break;
          }
          case 16: {

            workingHours_ = input.readInt32();
            break;
          }
          case 26: {
            grpc.services.schedule.Schedule.Builder subBuilder = null;
            if (schedule_ != null) {
              subBuilder = schedule_.toBuilder();
            }
            schedule_ = input.readMessage(grpc.services.schedule.Schedule.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(schedule_);
              schedule_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.service3.Service3Impl.internal_static_service3_AvailabilityResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.service3.Service3Impl.internal_static_service3_AvailabilityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.service3.AvailabilityResponse.class, grpc.services.service3.AvailabilityResponse.Builder.class);
  }

  public static final int IS_AVAILABLE_FIELD_NUMBER = 1;
  private boolean isAvailable_;
  /**
   * <pre>
   * Field indicating if staff is available during the specified time period
   * </pre>
   *
   * <code>bool is_available = 1;</code>
   */
  public boolean getIsAvailable() {
    return isAvailable_;
  }

  public static final int WORKING_HOURS_FIELD_NUMBER = 2;
  private int workingHours_;
  /**
   * <pre>
   * Field for the working hours of the staff during the specified time period
   * </pre>
   *
   * <code>int32 working_hours = 2;</code>
   */
  public int getWorkingHours() {
    return workingHours_;
  }

  public static final int SCHEDULE_FIELD_NUMBER = 3;
  private grpc.services.schedule.Schedule schedule_;
  /**
   * <pre>
   * Field containing the schedule of the staff during the specified time period
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 3;</code>
   */
  public boolean hasSchedule() {
    return schedule_ != null;
  }
  /**
   * <pre>
   * Field containing the schedule of the staff during the specified time period
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 3;</code>
   */
  public grpc.services.schedule.Schedule getSchedule() {
    return schedule_ == null ? grpc.services.schedule.Schedule.getDefaultInstance() : schedule_;
  }
  /**
   * <pre>
   * Field containing the schedule of the staff during the specified time period
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 3;</code>
   */
  public grpc.services.schedule.ScheduleOrBuilder getScheduleOrBuilder() {
    return getSchedule();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isAvailable_ != false) {
      output.writeBool(1, isAvailable_);
    }
    if (workingHours_ != 0) {
      output.writeInt32(2, workingHours_);
    }
    if (schedule_ != null) {
      output.writeMessage(3, getSchedule());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isAvailable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isAvailable_);
    }
    if (workingHours_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, workingHours_);
    }
    if (schedule_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSchedule());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.service3.AvailabilityResponse)) {
      return super.equals(obj);
    }
    grpc.services.service3.AvailabilityResponse other = (grpc.services.service3.AvailabilityResponse) obj;

    boolean result = true;
    result = result && (getIsAvailable()
        == other.getIsAvailable());
    result = result && (getWorkingHours()
        == other.getWorkingHours());
    result = result && (hasSchedule() == other.hasSchedule());
    if (hasSchedule()) {
      result = result && getSchedule()
          .equals(other.getSchedule());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAvailable());
    hash = (37 * hash) + WORKING_HOURS_FIELD_NUMBER;
    hash = (53 * hash) + getWorkingHours();
    if (hasSchedule()) {
      hash = (37 * hash) + SCHEDULE_FIELD_NUMBER;
      hash = (53 * hash) + getSchedule().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.service3.AvailabilityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service3.AvailabilityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.service3.AvailabilityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service3.AvailabilityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.service3.AvailabilityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Definition of the 'AvailabilityResponse' message with its fields
   * </pre>
   *
   * Protobuf type {@code service3.AvailabilityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.AvailabilityResponse)
      grpc.services.service3.AvailabilityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.service3.Service3Impl.internal_static_service3_AvailabilityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.service3.Service3Impl.internal_static_service3_AvailabilityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.service3.AvailabilityResponse.class, grpc.services.service3.AvailabilityResponse.Builder.class);
    }

    // Construct using grpc.services.service3.AvailabilityResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isAvailable_ = false;

      workingHours_ = 0;

      if (scheduleBuilder_ == null) {
        schedule_ = null;
      } else {
        schedule_ = null;
        scheduleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.service3.Service3Impl.internal_static_service3_AvailabilityResponse_descriptor;
    }

    @java.lang.Override
    public grpc.services.service3.AvailabilityResponse getDefaultInstanceForType() {
      return grpc.services.service3.AvailabilityResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.service3.AvailabilityResponse build() {
      grpc.services.service3.AvailabilityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.service3.AvailabilityResponse buildPartial() {
      grpc.services.service3.AvailabilityResponse result = new grpc.services.service3.AvailabilityResponse(this);
      result.isAvailable_ = isAvailable_;
      result.workingHours_ = workingHours_;
      if (scheduleBuilder_ == null) {
        result.schedule_ = schedule_;
      } else {
        result.schedule_ = scheduleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.service3.AvailabilityResponse) {
        return mergeFrom((grpc.services.service3.AvailabilityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.service3.AvailabilityResponse other) {
      if (other == grpc.services.service3.AvailabilityResponse.getDefaultInstance()) return this;
      if (other.getIsAvailable() != false) {
        setIsAvailable(other.getIsAvailable());
      }
      if (other.getWorkingHours() != 0) {
        setWorkingHours(other.getWorkingHours());
      }
      if (other.hasSchedule()) {
        mergeSchedule(other.getSchedule());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.service3.AvailabilityResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.service3.AvailabilityResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isAvailable_ ;
    /**
     * <pre>
     * Field indicating if staff is available during the specified time period
     * </pre>
     *
     * <code>bool is_available = 1;</code>
     */
    public boolean getIsAvailable() {
      return isAvailable_;
    }
    /**
     * <pre>
     * Field indicating if staff is available during the specified time period
     * </pre>
     *
     * <code>bool is_available = 1;</code>
     */
    public Builder setIsAvailable(boolean value) {
      
      isAvailable_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field indicating if staff is available during the specified time period
     * </pre>
     *
     * <code>bool is_available = 1;</code>
     */
    public Builder clearIsAvailable() {
      
      isAvailable_ = false;
      onChanged();
      return this;
    }

    private int workingHours_ ;
    /**
     * <pre>
     * Field for the working hours of the staff during the specified time period
     * </pre>
     *
     * <code>int32 working_hours = 2;</code>
     */
    public int getWorkingHours() {
      return workingHours_;
    }
    /**
     * <pre>
     * Field for the working hours of the staff during the specified time period
     * </pre>
     *
     * <code>int32 working_hours = 2;</code>
     */
    public Builder setWorkingHours(int value) {
      
      workingHours_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Field for the working hours of the staff during the specified time period
     * </pre>
     *
     * <code>int32 working_hours = 2;</code>
     */
    public Builder clearWorkingHours() {
      
      workingHours_ = 0;
      onChanged();
      return this;
    }

    private grpc.services.schedule.Schedule schedule_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.schedule.Schedule, grpc.services.schedule.Schedule.Builder, grpc.services.schedule.ScheduleOrBuilder> scheduleBuilder_;
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public boolean hasSchedule() {
      return scheduleBuilder_ != null || schedule_ != null;
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public grpc.services.schedule.Schedule getSchedule() {
      if (scheduleBuilder_ == null) {
        return schedule_ == null ? grpc.services.schedule.Schedule.getDefaultInstance() : schedule_;
      } else {
        return scheduleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public Builder setSchedule(grpc.services.schedule.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schedule_ = value;
        onChanged();
      } else {
        scheduleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public Builder setSchedule(
        grpc.services.schedule.Schedule.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        schedule_ = builderForValue.build();
        onChanged();
      } else {
        scheduleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public Builder mergeSchedule(grpc.services.schedule.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (schedule_ != null) {
          schedule_ =
            grpc.services.schedule.Schedule.newBuilder(schedule_).mergeFrom(value).buildPartial();
        } else {
          schedule_ = value;
        }
        onChanged();
      } else {
        scheduleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public Builder clearSchedule() {
      if (scheduleBuilder_ == null) {
        schedule_ = null;
        onChanged();
      } else {
        schedule_ = null;
        scheduleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public grpc.services.schedule.Schedule.Builder getScheduleBuilder() {
      
      onChanged();
      return getScheduleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    public grpc.services.schedule.ScheduleOrBuilder getScheduleOrBuilder() {
      if (scheduleBuilder_ != null) {
        return scheduleBuilder_.getMessageOrBuilder();
      } else {
        return schedule_ == null ?
            grpc.services.schedule.Schedule.getDefaultInstance() : schedule_;
      }
    }
    /**
     * <pre>
     * Field containing the schedule of the staff during the specified time period
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.schedule.Schedule, grpc.services.schedule.Schedule.Builder, grpc.services.schedule.ScheduleOrBuilder> 
        getScheduleFieldBuilder() {
      if (scheduleBuilder_ == null) {
        scheduleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.services.schedule.Schedule, grpc.services.schedule.Schedule.Builder, grpc.services.schedule.ScheduleOrBuilder>(
                getSchedule(),
                getParentForChildren(),
                isClean());
        schedule_ = null;
      }
      return scheduleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.AvailabilityResponse)
  }

  // @@protoc_insertion_point(class_scope:service3.AvailabilityResponse)
  private static final grpc.services.service3.AvailabilityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.service3.AvailabilityResponse();
  }

  public static grpc.services.service3.AvailabilityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AvailabilityResponse>
      PARSER = new com.google.protobuf.AbstractParser<AvailabilityResponse>() {
    @java.lang.Override
    public AvailabilityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AvailabilityResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AvailabilityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AvailabilityResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.service3.AvailabilityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

