// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.services.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_UpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\032\016schedule.pro" +
      "to\"[\n\023AvailabilityRequest\022\022\n\nstart_date\030" +
      "\001 \001(\t\022\020\n\010end_date\030\002 \001(\t\022\020\n\010position\030\003 \001(" +
      "\t\022\014\n\004name\030\004 \001(\t\"i\n\024AvailabilityResponse\022" +
      "\024\n\014is_available\030\001 \001(\010\022\025\n\rworking_hours\030\002" +
      " \001(\005\022$\n\010schedule\030\003 \001(\0132\022.schedule.Schedu" +
      "le\";\n\rUpdateRequest\022*\n\016staff_schedule\030\001 " +
      "\001(\0132\022.schedule.Schedule\"P\n\016UpdateRespons" +
      "e\022\022\n\nis_updated\030\001 \001(\010\022*\n\016staff_schedule\030" +
      "\002 \001(\0132\022.schedule.Schedule2\270\001\n\021StaffAvail" +
      "ability\022X\n\021CheckAvailability\022\035.service3." +
      "AvailabilityRequest\032\036.service3.Availabil" +
      "ityResponse\"\000(\0010\001\022I\n\016UpdateSchedule\022\027.se" +
      "rvice3.UpdateRequest\032\030.service3.UpdateRe" +
      "sponse\"\000(\0010\001B(\n\026grpc.services.service3B\014" +
      "Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.services.schedule.ScheduleOuterClass.getDescriptor(),
        }, assigner);
    internal_static_service3_AvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_AvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailabilityRequest_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "Position", "Name", });
    internal_static_service3_AvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_AvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AvailabilityResponse_descriptor,
        new java.lang.String[] { "IsAvailable", "WorkingHours", "Schedule", });
    internal_static_service3_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_UpdateRequest_descriptor,
        new java.lang.String[] { "StaffSchedule", });
    internal_static_service3_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_UpdateResponse_descriptor,
        new java.lang.String[] { "IsUpdated", "StaffSchedule", });
    grpc.services.schedule.ScheduleOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
