// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.services.service1;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Field for the name for login
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Field for the name for login
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Field for the position for login
   * </pre>
   *
   * <code>string position = 2;</code>
   */
  java.lang.String getPosition();
  /**
   * <pre>
   * Field for the position for login
   * </pre>
   *
   * <code>string position = 2;</code>
   */
  com.google.protobuf.ByteString
      getPositionBytes();
}
