// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.services.service1;

/**
 * <pre>
 * Definition of the 'ScheduleRequest' message with its fields
 * </pre>
 *
 * Protobuf type {@code service1.ScheduleRequest}
 */
public  final class ScheduleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.ScheduleRequest)
    ScheduleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScheduleRequest.newBuilder() to construct.
  private ScheduleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScheduleRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScheduleRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.services.schedule.Schedule.Builder subBuilder = null;
            if (schedule_ != null) {
              subBuilder = schedule_.toBuilder();
            }
            schedule_ = input.readMessage(grpc.services.schedule.Schedule.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(schedule_);
              schedule_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.service1.Service1Impl.internal_static_service1_ScheduleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.service1.Service1Impl.internal_static_service1_ScheduleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.service1.ScheduleRequest.class, grpc.services.service1.ScheduleRequest.Builder.class);
  }

  public static final int SCHEDULE_FIELD_NUMBER = 1;
  private grpc.services.schedule.Schedule schedule_;
  /**
   * <pre>
   * Field for the schedule to be registered
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 1;</code>
   */
  public boolean hasSchedule() {
    return schedule_ != null;
  }
  /**
   * <pre>
   * Field for the schedule to be registered
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 1;</code>
   */
  public grpc.services.schedule.Schedule getSchedule() {
    return schedule_ == null ? grpc.services.schedule.Schedule.getDefaultInstance() : schedule_;
  }
  /**
   * <pre>
   * Field for the schedule to be registered
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 1;</code>
   */
  public grpc.services.schedule.ScheduleOrBuilder getScheduleOrBuilder() {
    return getSchedule();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schedule_ != null) {
      output.writeMessage(1, getSchedule());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schedule_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSchedule());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.service1.ScheduleRequest)) {
      return super.equals(obj);
    }
    grpc.services.service1.ScheduleRequest other = (grpc.services.service1.ScheduleRequest) obj;

    boolean result = true;
    result = result && (hasSchedule() == other.hasSchedule());
    if (hasSchedule()) {
      result = result && getSchedule()
          .equals(other.getSchedule());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSchedule()) {
      hash = (37 * hash) + SCHEDULE_FIELD_NUMBER;
      hash = (53 * hash) + getSchedule().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.service1.ScheduleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service1.ScheduleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.service1.ScheduleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.service1.ScheduleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.service1.ScheduleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Definition of the 'ScheduleRequest' message with its fields
   * </pre>
   *
   * Protobuf type {@code service1.ScheduleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.ScheduleRequest)
      grpc.services.service1.ScheduleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.service1.Service1Impl.internal_static_service1_ScheduleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.service1.Service1Impl.internal_static_service1_ScheduleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.service1.ScheduleRequest.class, grpc.services.service1.ScheduleRequest.Builder.class);
    }

    // Construct using grpc.services.service1.ScheduleRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (scheduleBuilder_ == null) {
        schedule_ = null;
      } else {
        schedule_ = null;
        scheduleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.service1.Service1Impl.internal_static_service1_ScheduleRequest_descriptor;
    }

    @java.lang.Override
    public grpc.services.service1.ScheduleRequest getDefaultInstanceForType() {
      return grpc.services.service1.ScheduleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.service1.ScheduleRequest build() {
      grpc.services.service1.ScheduleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.service1.ScheduleRequest buildPartial() {
      grpc.services.service1.ScheduleRequest result = new grpc.services.service1.ScheduleRequest(this);
      if (scheduleBuilder_ == null) {
        result.schedule_ = schedule_;
      } else {
        result.schedule_ = scheduleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.service1.ScheduleRequest) {
        return mergeFrom((grpc.services.service1.ScheduleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.service1.ScheduleRequest other) {
      if (other == grpc.services.service1.ScheduleRequest.getDefaultInstance()) return this;
      if (other.hasSchedule()) {
        mergeSchedule(other.getSchedule());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.service1.ScheduleRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.service1.ScheduleRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.services.schedule.Schedule schedule_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.schedule.Schedule, grpc.services.schedule.Schedule.Builder, grpc.services.schedule.ScheduleOrBuilder> scheduleBuilder_;
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public boolean hasSchedule() {
      return scheduleBuilder_ != null || schedule_ != null;
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public grpc.services.schedule.Schedule getSchedule() {
      if (scheduleBuilder_ == null) {
        return schedule_ == null ? grpc.services.schedule.Schedule.getDefaultInstance() : schedule_;
      } else {
        return scheduleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public Builder setSchedule(grpc.services.schedule.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schedule_ = value;
        onChanged();
      } else {
        scheduleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public Builder setSchedule(
        grpc.services.schedule.Schedule.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        schedule_ = builderForValue.build();
        onChanged();
      } else {
        scheduleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public Builder mergeSchedule(grpc.services.schedule.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (schedule_ != null) {
          schedule_ =
            grpc.services.schedule.Schedule.newBuilder(schedule_).mergeFrom(value).buildPartial();
        } else {
          schedule_ = value;
        }
        onChanged();
      } else {
        scheduleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public Builder clearSchedule() {
      if (scheduleBuilder_ == null) {
        schedule_ = null;
        onChanged();
      } else {
        schedule_ = null;
        scheduleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public grpc.services.schedule.Schedule.Builder getScheduleBuilder() {
      
      onChanged();
      return getScheduleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    public grpc.services.schedule.ScheduleOrBuilder getScheduleOrBuilder() {
      if (scheduleBuilder_ != null) {
        return scheduleBuilder_.getMessageOrBuilder();
      } else {
        return schedule_ == null ?
            grpc.services.schedule.Schedule.getDefaultInstance() : schedule_;
      }
    }
    /**
     * <pre>
     * Field for the schedule to be registered
     * </pre>
     *
     * <code>.schedule.Schedule schedule = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.schedule.Schedule, grpc.services.schedule.Schedule.Builder, grpc.services.schedule.ScheduleOrBuilder> 
        getScheduleFieldBuilder() {
      if (scheduleBuilder_ == null) {
        scheduleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.services.schedule.Schedule, grpc.services.schedule.Schedule.Builder, grpc.services.schedule.ScheduleOrBuilder>(
                getSchedule(),
                getParentForChildren(),
                isClean());
        schedule_ = null;
      }
      return scheduleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.ScheduleRequest)
  }

  // @@protoc_insertion_point(class_scope:service1.ScheduleRequest)
  private static final grpc.services.service1.ScheduleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.service1.ScheduleRequest();
  }

  public static grpc.services.service1.ScheduleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScheduleRequest>
      PARSER = new com.google.protobuf.AbstractParser<ScheduleRequest>() {
    @java.lang.Override
    public ScheduleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScheduleRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScheduleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScheduleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.service1.ScheduleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

