// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.services.service1;

public interface ScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Field indicating if the schedule is registered
   * </pre>
   *
   * <code>bool registered = 1;</code>
   */
  boolean getRegistered();

  /**
   * <pre>
   * Field containing the registered schedule
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 2;</code>
   */
  boolean hasSchedule();
  /**
   * <pre>
   * Field containing the registered schedule
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 2;</code>
   */
  grpc.services.schedule.Schedule getSchedule();
  /**
   * <pre>
   * Field containing the registered schedule
   * </pre>
   *
   * <code>.schedule.Schedule schedule = 2;</code>
   */
  grpc.services.schedule.ScheduleOrBuilder getScheduleOrBuilder();
}
